### ISSUE TITLE
unknown field 'Addrs' in struct literal of type client.Config

### ISSUE THREAD

**Issue by qiankun11516** [buraksezer/olric#110]
When I try to run olric client with the sample code, I meet this error:
./client_apply.go:14:3: unknown field 'Addrs' in struct literal of type client.Config
./client_apply.go:15:3: unknown field 'MaxConn' in struct literal of type client.Config

I did not find any definition about Addrs in the Config, so how can I solve it?

**Comment by qiankun11516** [comment]
@buraksezer

**Comment by buraksezer** [comment]
Hi @qiankun11516 

It looks like your Golang environment doesn't configured properly. In addition that current stable version of Olric is [v0.3.9](https://github.com/buraksezer/olric/releases/tag/v0.3.9). If you try to build and run the latest version, you may encounter undefined behaviors and problems. 

With a properly configured Golang environment:

```sh
go get github.com/buraksezer/olric@v0.3.9
```

**Comment by qiankun11516** [comment]
> Hi @qiankun11516
> 
> It looks like your Golang environment doesn't configured properly. In addition that current stable version of Olric is [v0.3.9](https://github.com/buraksezer/olric/releases/tag/v0.3.9). If you try to build and run the latest version, you may encounter undefined behaviors and problems.
> 
> With a properly configured Golang environment:
> 
> ```shell
> go get github.com/buraksezer/olric@v0.3.9
> ```

**Comment by qiankun11516** [comment]
Hi @buraksezer, thanks for your reply.
I am new with Go. So can you give some further guide. It would be very helpful.
My Golang config is as following:
[root@iZrj9auxi4brx5diccf3ybZ src]# echo $GOROOT
/usr/lib/golang
[root@iZrj9auxi4brx5diccf3ybZ src]# echo $GOPATH
/root/workspace
[root@iZrj9auxi4brx5diccf3ybZ src]# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/usr/bin/go/bin:/root/workspace/bin:/usr/bin/golang/bin:/root/workspace/bin:/usr/lib/golang/bin:/root/workspace/bin:/usr/lib/golang/bin:/root/workspace/bin

I also execute the installation according to [Installing](https://github.com/buraksezer/olric#installing).
The $GOPATH/src is as following after installation
[root@iZrj9auxi4brx5diccf3ybZ src]#cd $GOPATH/src
[root@iZrj9auxi4brx5diccf3ybZ src]#ls
github.com  golang.org  gopkg.in  hello.go  olric  olric-client.go  olric-simple.go

olricd can work normally. However, I still cannot compile my client sample code, the error is as following:
[root@iZrj9auxi4brx5diccf3ybZ src]#go run olric-client.go
# command-line-arguments
./olric-client.go:14:3: unknown field 'Addrs' in struct literal of type client.Config
./olric-client.go:15:3: unknown field 'MaxConn' in struct literal of type client.Config

**Comment by qiankun11516** [comment]
> Hi @qiankun11516
> 
> It looks like your Golang environment doesn't configured properly. In addition that current stable version of Olric is [v0.3.9](https://github.com/buraksezer/olric/releases/tag/v0.3.9). If you try to build and run the latest version, you may encounter undefined behaviors and problems.
> 
> With a properly configured Golang environment:
> 
> ```shell
> go get github.com/buraksezer/olric@v0.3.9
> ```

![image](https://user-images.githubusercontent.com/14502050/126157724-dc134126-11e8-43a7-87d3-d4bfe3dabfb7.png)

If I understand correct, there is no Addrs field in the client.Config, which is the root cause of this error.
If there is something wrong, please give me more guide.
Thanks!

**Comment by buraksezer** [comment]
Hi @qiankun11516 

I'm so sorry for the inconvenience. This is my bad. You hit an outdated portion of the documentation. I have just released a new version to update the documentation. A proper client configuration should look like the following:

```go
import (
	"github.com/buraksezer/olric/client"
	"github.com/buraksezer/olric/config"
)
...
...
var clientConfig = &client.Config{
    Servers:     []string{"localhost:3320"},
    Serializer:  serializer.NewMsgpackSerializer(),
    Client:      config.NewClient(),
}
```

Update to the latest version: 

```shell
go get github.com/buraksezer/olric@v0.3.11
```

Updated docs: https://github.com/buraksezer/olric/blob/v0.3.11/client/README.md#setup

**Comment by qiankun11516** [comment]
Hi @buraksezer 
Thank you for your reply. The previous errors are gone, but I encounter new one and try to fix it.
Can you also update the [Sample Code](https://github.com/buraksezer/olric/blob/v0.3.11/client/README.md#sample-code) as well to provide a complete client-side guide.
It would be very helpful.
Thank you!

**Comment by qiankun11516** [comment]
I modify the client sample code as following:
package main

import (
        "fmt"
        "log"
        "strconv"

        "github.com/buraksezer/olric/client"
        "github.com/buraksezer/olric/config"
        "github.com/buraksezer/olric/serializer"
)

func main() {
        cc := &client.Config{
                Servers:     []string{"198.11.172.14:30448"},
                Serializer:  serializer.NewMsgpackSerializer(),
                Client:      config.NewClient(),
        }
        c, err := client.New(cc)
        if err != nil {
                log.Fatalf("Olric client returned error: %s", err)
        }
        defer c.Close()

        // Create a DMap instance
        dm := c.NewDMap("my-dmap")
        for i := 0; i < 10; i++ {
                key := strconv.Itoa(i)
                value := strconv.Itoa(i * 2)
                if err = dm.Put(key, value); err != nil {
                        log.Fatalf("put failed for %s: %s", key, err)
                        fmt.Printf("Failed\n")
                }
                fmt.Printf("[PUT] Key: %s, Value: %s\n", key, value)
        }

        fmt.Printf("\n")
        //value, err := dm.GetEntry("1")
        value, err := dm.Get("1")
        fmt.Printf("[GET] Value: %s\n", value)
}

However, I get the following error:
![image](https://user-images.githubusercontent.com/14502050/126257959-e93386f5-c98d-4d51-ad22-d64c52c00c69.png)
I tried both dm.GetEntry("1") and dm.Get("1"). Both return the similar error.
It is the client side bug, right? Can you give me some guide to fix it?

**Comment by buraksezer** [comment]
Hi @qiankun11516 

I couldn't reproduce the error against `v0.3.11` with the following code. It's almost identical to your sample. Could you please give more information about your environment? I'm trying to reproduce it on a decent Macbook Pro. It should also work without any problem on a decent 64 bit Linux system. Olric may behave different on the other architectures such as 32 bit ARM. 

```go
package main

import (
	"fmt"
	"log"
	"strconv"

	"github.com/buraksezer/olric/client"
	"github.com/buraksezer/olric/config"
	"github.com/buraksezer/olric/serializer"
)

func main() {
	var cc = &client.Config{
		Servers:    []string{"192.168.1.7:3320"},
		Serializer: serializer.NewMsgpackSerializer(),
		Client:     config.NewClient(),
	}

	// Create a new client instance
	c, err := client.New(cc)
	if err != nil {
		log.Fatalf("Olric client returned error: %s", err)
	}
	defer c.Close()

	// Create a DMap instance
	dm := c.NewDMap("my-dmap")
	for i := 0; i < 10; i++ {
		key := strconv.Itoa(i)
		value := strconv.Itoa(i * 2)
		if err = dm.Put(key, value); err != nil {
			log.Fatalf("put failed for %s: %s", key, err)
		}
		fmt.Printf("[PUT] Key: %s, Value: %s\n", key, value)
	}

	fmt.Printf("\n")

	for i := 0; i < 10; i++ {
		key := strconv.Itoa(i)
		value, err := dm.Get(key)
		if err != nil {
			log.Fatalf("get failed for %s: %s", err)
		}
		fmt.Printf("[GET] Key: %s, Value: %s\n", key, value)
	}

	fmt.Printf("\n")

	key := "1"
	value, err := dm.Get(key)
	if err != nil {
		log.Fatalf("get failed for %s: %s", err)
	}
	fmt.Printf("[GET] Key: %s, Value: %s\n", key, value)

}
```

**Comment by qiankun11516** [comment]
Hi @buraksezer 
With the new sample code, I still have the same error.
I use CentOS 7.6 and my environment is as following:

[root@iZrj9auxi4brx5diccf3ybZ src]# go version
go version go1.15.5 linux/amd64

[root@iZrj9auxi4brx5diccf3ybZ src]# uname -r
3.10.0-957.21.3.el7.x86_64

[root@iZrj9auxi4brx5diccf3ybZ src]# uname -a
Linux iZrj9auxi4brx5diccf3ybZ 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The PUT operations work well mean that the communication with server is OK, right?
So it should be the client side problem.
I think maybe the Golang version makes some difference?

**Comment by buraksezer** [comment]
> The PUT operations work well mean that the communication with server is OK, right?

Yes, that's right. 

I just wonder that what kind of system is that? I mean Linux 3.10 is an ancient version and it is no longer supported. You may have encountered an old bug in Golang network stack. Do you have any opportunity to upgrade your system to test this scenario?

**Comment by buraksezer** [comment]
I'm closing this issue due to a lack of user response.
